language: php
php:
  - '7.1'
  - '7.2'
  - '7.4'
os: ubuntu
dist: bionic
services:
  - mysql
script:
  - web/index.php
  - web/home/search_all.php
  - web/home/search_select.php
  - web/home/show_all.php
